actions: cleanup

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,6 +1,5 @@
 # https://lgug2z.com/articles/building-and-privately-caching-x86-and-aarch64-nixos-systems-on-github-actions/
 name: "build"
-
 on:
   push:
     branches:
@@ -8,60 +7,39 @@ on:
   pull_request:
     branches:
       - main
-
 permissions:
   contents: read
   models: read
-
 concurrency: 
   group: ${{ github.ref }}
   cancel-in-progress: true
-
 jobs:
   build:
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
-      # Here we specify the matrix of our hosts and their target platform architectures
       matrix:
-        machine:
-          - host: laptop
-            platform: x86-64-linux
-          - host: nas
-            platform: x86-64-linux
-          - host: vps
-            platform: aarch64-linux
+        target: [flake-check, laptop, nas, vps]
     steps:
       - uses: actions/checkout@v4
-
-      # We only run this if we are building an aarch64-linux system
-      - if: matrix.machine.platform == 'aarch64-linux'
-        uses: docker/setup-qemu-action@v3
-
+      - uses: docker/setup-qemu-action@v3
       - run: |
           sudo mkdir -p /etc/nix
           echo "machine cache.lorenzbischof.com password ${{ secrets.ATTIC_TOKEN }}" | sudo tee /etc/nix/netrc > /dev/null
-
       - uses: wimpysworld/nothing-but-nix@main
         with:
           hatchet-protocol: holster
-
       - uses: cachix/install-nix-action@v31
         with:
           # We set our custom GitHub token for any private flake inputs we might have
           github_access_token: ${{ secrets.GH_TOKEN }}
-          # We add all the config for extra platforms, other binary caches and to raise the number of connections that can be made
           extra_nix_config: |
             fallback = true
             http-connections = 128
             max-substitution-jobs = 128
             extra-platforms = aarch64-linux
-            substituters = https://cache.lorenzbischof.com/system?priority=42 https://nix-community.cachix.org?priority=41 https://cache.nixos.org/
-            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= system:DAJL6xmsmoUmZOeGL8XxrEWF5pdtFGMW2+cOGyYaqgU= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
-
-      # https://determinate.systems/posts/magic-nix-cache-free-tier-eol/
-      #- uses: DeterminateSystems/magic-nix-cache-action@main
-
+            substituters = https://cache.lorenzbischof.com/system?priority=42 https://cache.nixos.org/
+            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= system:DAJL6xmsmoUmZOeGL8XxrEWF5pdtFGMW2+cOGyYaqgU=
       - name: Tailscale
         uses: tailscale/github-action@v3
         with:
@@ -69,17 +47,23 @@ jobs:
           oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
           tags: tag:cicd
           use-cache: 'true'
-
-      - name: Build and push system
+      - name: Build and push
         run: |
           nix run nixpkgs#attic-client login cache https://cache.lorenzbischof.com ${{ secrets.ATTIC_TOKEN }}
-          nix build .#nixosConfigurations.${{ matrix.machine.host }}.config.system.build.toplevel 2>&1 | tee build.log
-          nix run nixpkgs#attic-client push system result
-
-      - name: Process failure
-        if: failure()
+          if [ "${{ matrix.target }}" = "flake-check" ]; then
+            nix flake check
+          else
+            nix build .#nixosConfigurations.${{ matrix.target }}.config.system.build.toplevel
+            nix run nixpkgs#attic-client push system result
+          fi
+    
+  failure-alert:
+    runs-on: ubuntu-latest
+    needs: [build]
+    if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
+    steps:
+      - name: Conditionally Fail Required Check
+        shell: bash
         run: |
-          gh extension install github/gh-models
-          cat build.log | sed -n '/error:/,$p' | tail | gh models run openai/gpt-4o "This is the result of a nixosConfiguration nix-build. Summarize the error and suggest a possible fix, if you are pretty certain it might help" 
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          echo "::error Some required job has failed!"
+          exit 1
